//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergySimplyLib.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_121539_alkeshpatelfEntities : DbContext
    {
        public DB_121539_alkeshpatelfEntities()
            : base("name=DB_121539_alkeshpatelfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<EnergyPlan> EnergyPlans { get; set; }
        public virtual DbSet<EnergyFile> EnergyFiles { get; set; }
        public virtual DbSet<EnergySavedFile> EnergySavedFiles { get; set; }
    }
}
