//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergySimplyLib.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnergyPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnergyPlan()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int EnergyPlanId { get; set; }
        public string EnergyPlanName { get; set; }
        public decimal EnergyPlanFixedCost { get; set; }
        public decimal EnergyPlanVarCost { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
